/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hardware/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregate hardware status (camera + tripod + calibration) */
        get: operations["getHardwareStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/camera/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query all current camera settings */
        get: operations["getCameraSettings"];
        /** Apply a partial camera settings update */
        put: operations["putCameraSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/camera/capture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger a one-shot still capture (test capture) */
        post: operations["postCameraCapture"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/camera/captures/{capture_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download a previously captured one-shot image */
        get: operations["getCaptureFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/camera/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Single-shot live-view preview frame */
        get: operations["getCameraPreview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/camera/preview/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Continuous MJPEG preview stream (browser-friendly)
         * @description Returns `multipart/x-mixed-replace; boundary=frame`. Suitable for an
         *     `<img>` tag. Capped server-side to ≤ 5 fps on Pi Zero 2 W to keep CPU
         *     below 30 % during preview. Closing the connection stops streaming.
         */
        get: operations["getCameraPreviewStream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tripod/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current tripod state (position, drivers, calibration) */
        get: operations["getTripodStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tripod/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move to an absolute (pan, tilt) target */
        post: operations["postTripodMove"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tripod/nudge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply a relative pan / tilt nudge (manual control) */
        post: operations["postTripodNudge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tripod/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set the current physical position as (0°, 0°)
         * @description Software-only homing. Flips calibration state from `unknown` to `homed` (FR-040).
         */
        post: operations["postTripodHome"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tripod/drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Enable or disable stepper drivers
         * @description Disabling resets the known position; calibration becomes `unknown` (FR-011).
         */
        put: operations["putTripodDrivers"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tripod/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Emergency stop — halt all motion immediately (FR-008) */
        post: operations["postTripodStop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/timelapse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Launch a timelapse job */
        post: operations["postTimelapseJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/video-pan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Launch a video-pan job (motion + REC sync, FR-019/020) */
        post: operations["postVideoPanJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the currently running job, if any */
        get: operations["getActiveJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a job snapshot */
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cooperative stop (current capture finishes, motion halts) */
        post: operations["postJobStop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List sessions, newest first */
        get: operations["getSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a session record */
        get: operations["getSession"];
        put?: never;
        post?: never;
        /** Delete a session and its assets */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reload the configuration that produced this session (FR-024) */
        get: operations["getSessionConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/assemble": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assemble (or re-assemble) the session video (FR-025) */
        post: operations["postSessionAssemble"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/assets/{asset_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download a session asset (frame, video, metadata) */
        get: operations["getSessionAsset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /**
             * @description Stable machine-readable code (snake_case).
             * @example validation_failed
             * @example job_already_running
             * @example calibration_required
             * @example camera_disconnected
             * @example tilt_limit_exceeded
             * @example protocol_version_mismatch
             */
            error: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        Health: {
            /** @enum {string} */
            status: "ok";
            /** @description Host application semver. */
            version: string;
            uptime_s: number;
            active_job_id?: string | null;
        };
        HardwareStatus: {
            camera: components["schemas"]["CameraStatus"];
            tripod: components["schemas"]["TripodStatus"];
            calibration: {
                /** @enum {string} */
                state: "unknown" | "homed";
                set_at?: string | null;
            };
            active_job_id?: string | null;
            /** Format: date-time */
            updated_at: string;
        };
        CameraStatus: {
            /** @enum {string} */
            state: "connected" | "disconnected" | "error";
            model?: string | null;
            last_error?: string | null;
            battery_pct?: number | null;
        };
        /** @description Map of gphoto2 widget path → current value/type/choices. */
        CameraSettings: {
            [key: string]: {
                /** @enum {string} */
                type: "TEXT" | "RANGE" | "TOGGLE" | "RADIO" | "MENU" | "DATE" | "BUTTON" | "UNKNOWN";
                /** @description Current value (string|number|bool|null). */
                current: string | number | boolean | null;
                choices?: string[] | null;
                range?: {
                    min?: number;
                    max?: number;
                    step?: number;
                } | null;
            };
        };
        CameraSettingsUpdate: {
            settings: {
                [key: string]: string | number | boolean;
            };
            /**
             * @default strict
             * @enum {string}
             */
            step_policy: "strict" | "snap";
        };
        CaptureRequest: {
            /**
             * @description When `false`, skip the AF motor (matches `capture_image_no_af`).
             * @default false
             */
            autofocus: boolean;
            /** @description Optional — store the test capture as an asset on a session. */
            save_to_session?: string | null;
        };
        CaptureResult: {
            /** Format: uuid */
            capture_id: string;
            content_type: string;
            /** Format: date-time */
            captured_at: string;
            size_bytes: number;
            /**
             * Format: uri-reference
             * @description Path to fetch the binary (`/api/camera/captures/{id}`).
             */
            download_url?: string;
        };
        TripodStatus: {
            /** @enum {string} */
            state: "connected" | "disconnected" | "error";
            firmware_version?: string | null;
            /** @default true */
            protocol_compatible: boolean;
            drivers_enabled: boolean;
            position_pan_deg: number;
            position_tilt_deg: number;
            tilt_min_deg?: number | null;
            tilt_max_deg?: number | null;
            last_error?: string | null;
        };
        AbsoluteMoveRequest: {
            pan_deg: number;
            tilt_deg: number;
        };
        RelativeNudgeRequest: {
            /** @default 0 */
            delta_pan_deg: number;
            /** @default 0 */
            delta_tilt_deg: number;
        };
        /**
         * @description Full session configuration. See `contracts/config-schema.md` for the
         *     annotated YAML form. The same shape is accepted as YAML on filesystem
         *     and as JSON over HTTP.
         */
        Configuration: {
            metadata: components["schemas"]["ConfigurationMetadata"];
            camera: components["schemas"]["CameraConfig"];
            tripod: components["schemas"]["TripodConfig"];
            safety: components["schemas"]["SafetyConfig"];
            output: components["schemas"]["OutputConfig"];
            sequence: components["schemas"]["TimelapseSequenceConfig"] | components["schemas"]["VideoPanSequenceConfig"];
        };
        ConfigurationMetadata: {
            name: string;
            description?: string;
            tags?: string[];
            /** Format: date-time */
            created_at?: string;
        };
        CameraConfig: {
            model_substring?: string;
            settings?: {
                [key: string]: string | number | boolean;
            };
            /**
             * @default camera-default
             * @enum {string}
             */
            image_format: "camera-default" | "jpeg-only" | "raw-only" | "raw+jpeg";
        };
        TripodConfig: {
            serial: {
                /** @description Path or socket:// URL */
                port: string;
                /** @default 9600 */
                baudrate: number;
                /** @default 1 */
                timeout: number;
                /** @default 1 */
                write_timeout: number;
                /** @default 2 */
                reconnect_interval: number;
                /** @default 5 */
                max_retries: number;
            };
            /**
             * @default 16
             * @enum {integer}
             */
            microstep: 1 | 2 | 4 | 8 | 16;
            /** @default 1 */
            expected_protocol_major: number;
        };
        SafetyConfig: {
            tilt_min_deg: number;
            tilt_max_deg: number;
            /** @default 2 */
            move_timeout_margin_s: number;
            /** @default 200000000 */
            disk_min_free_bytes: number;
            /** @default 20000000 */
            disk_avg_frame_bytes: number;
        };
        OutputConfig: {
            output_dir: string;
            /** @default frame_{index:04d}{ext} */
            frame_filename_template: string;
            /**
             * @default auto
             * @enum {string}
             */
            metadata_strategy: "exif" | "csv" | "auto";
            video?: {
                /** @default true */
                assemble: boolean;
                /** @default 25 */
                fps: number;
                /**
                 * @default mp4-h264
                 * @enum {string}
                 */
                format: "mp4-h264" | "mov-prores" | "webm-vp9";
                ffmpeg_extra?: string;
            };
        };
        TimelapseSequenceConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "timelapse";
            total_frames: number;
            interval_s: number;
            settle_time_s: number;
            start: components["schemas"]["Angles"];
            target: components["schemas"]["Angles"];
        };
        VideoPanSequenceConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "video_pan";
            duration_s: number;
            start: components["schemas"]["Angles"];
            target: components["schemas"]["Angles"];
        };
        Angles: {
            pan_deg: number;
            tilt_deg: number;
        };
        Job: {
            /** Format: uuid */
            job_id: string;
            /** @enum {string} */
            kind: "timelapse" | "video_pan";
            /** @enum {string} */
            status: "pending" | "running" | "completed" | "failed" | "stopped";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            finished_at?: string | null;
            progress?: components["schemas"]["JobProgress"];
            last_position?: components["schemas"]["Angles"];
            fault?: components["schemas"]["FaultEvent"];
            /** @default 0 */
            cadence_warnings: number;
            /** Format: uuid */
            session_id?: string | null;
        };
        JobProgress: {
            frames_completed?: number;
            frames_total?: number;
            motion_pct?: number;
            /** Format: date-time */
            estimated_finish_at?: string | null;
        };
        FaultEvent: {
            /** @enum {string} */
            code: "camera_disconnected" | "camera_capture_failed" | "motor_stall" | "serial_lost" | "disk_full" | "tilt_limit" | "calibration_required" | "config_invalid" | "user_stopped";
            message: string;
            frame_index?: number | null;
            last_position?: components["schemas"]["Angles"];
            /** @default false */
            recoverable: boolean;
        };
        SessionSummary: {
            /** Format: uuid */
            session_id: string;
            /** @enum {string} */
            kind: "timelapse" | "video_pan";
            /** @enum {string} */
            status: "completed" | "failed" | "stopped";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            finished_at?: string | null;
            name?: string;
            tags?: string[];
            frames_captured?: number;
            frames_planned?: number;
            flags?: {
                [key: string]: boolean;
            };
        };
        Session: components["schemas"]["SessionSummary"] & {
            configuration: components["schemas"]["Configuration"];
            assets: components["schemas"]["SessionAsset"][];
            fault?: components["schemas"]["FaultEvent"];
        };
        SessionAsset: {
            path: string;
            /** @enum {string} */
            kind: "frame" | "video" | "metadata" | "preview";
            size_bytes?: number | null;
            content_type?: string | null;
            label?: string | null;
        };
    };
    responses: {
        /** @description Request body or query failed validation. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource does not exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Camera is disconnected or in error state. */
        CameraUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Tripod is disconnected, in error state, or protocol-incompatible. */
        TripodUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Host is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getHardwareStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current snapshot. The web UI subscribes to `hardware.status` over WebSocket for live updates. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HardwareStatus"];
                };
            };
        };
    };
    getCameraSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Map of gphoto2 widget paths to current values, types, and choices. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraSettings"];
                };
            };
            503: components["responses"]["CameraUnavailable"];
        };
    };
    putCameraSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CameraSettingsUpdate"];
            };
        };
        responses: {
            /** @description Settings applied. The response echoes the resulting settings map. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraSettings"];
                };
            };
            400: components["responses"]["ValidationError"];
            503: components["responses"]["CameraUnavailable"];
        };
    };
    postCameraCapture: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CaptureRequest"];
            };
        };
        responses: {
            /** @description Capture metadata; binary content fetched via `GET /api/camera/captures/{id}`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureResult"];
                };
            };
            /** @description A running job currently owns the hardware lock. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            503: components["responses"]["CameraUnavailable"];
        };
    };
    getCaptureFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                capture_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image bytes; content-type matches the camera output (image/jpeg or vendor RAW). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                    "image/x-canon-cr3": string;
                    "image/x-nikon-nef": string;
                    "application/octet-stream": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getCameraPreview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One JPEG. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                };
            };
            503: components["responses"]["CameraUnavailable"];
        };
    };
    getCameraPreviewStream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description MJPEG stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "multipart/x-mixed-replace": string;
                };
            };
            503: components["responses"]["CameraUnavailable"];
        };
    };
    getTripodStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripodStatus"];
                };
            };
            503: components["responses"]["TripodUnavailable"];
        };
    };
    postTripodMove: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AbsoluteMoveRequest"];
            };
        };
        responses: {
            /** @description Move completed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripodStatus"];
                };
            };
            400: components["responses"]["ValidationError"];
            /** @description Hardware locked by an active job. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Calibration is `unknown` (FR-041) and the move is automated. Manual nudges are still allowed via `/api/tripod/nudge`. */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Tilt outside the configured safety window (FR-009). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    postTripodNudge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RelativeNudgeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripodStatus"];
                };
            };
            400: components["responses"]["ValidationError"];
            /** @description Hardware locked. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Resulting tilt would exceed the safety window. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    postTripodHome: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripodStatus"];
                };
            };
            503: components["responses"]["TripodUnavailable"];
        };
    };
    putTripodDrivers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    enabled: boolean;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripodStatus"];
                };
            };
        };
    };
    postTripodStop: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripodStatus"];
                };
            };
        };
    };
    postTimelapseJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Configuration"];
            };
        };
        responses: {
            /** @description Job accepted; subscribe to `/ws/events` topic `job.<id>.*` for progress. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            400: components["responses"]["ValidationError"];
            /** @description Another job is running. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Calibration required (FR-041). */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Hardware unavailable (camera or tripod disconnected). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    postVideoPanJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Configuration"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            400: components["responses"]["ValidationError"];
            /** @description Another job is running. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Calibration required. */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getActiveJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"] | null;
                };
            };
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    postJobStop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getSessions: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                tag?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["SessionSummary"][];
                        total: number;
                    };
                };
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    getSessionConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The exact `Configuration` document. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Configuration"];
                    "application/x-yaml": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    postSessionAssemble: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    fps?: number;
                    ffmpeg_extra?: string;
                    /** @enum {string} */
                    format?: "mp4-h264" | "mov-prores" | "webm-vp9";
                };
            };
        };
        responses: {
            /** @description Assembly job started; subscribe to `/ws/events` topic `session.<id>.assemble` for progress. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Another job (capture or assembly) is running. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getSessionAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                asset_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Asset bytes (content-type per asset). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
