[mypy]
python_version = 3.12
strict = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_unreachable = True
disallow_untyped_decorators = False
plugins = pydantic.mypy

[mypy-gphoto2.*]
ignore_missing_imports = True

[mypy-piexif.*]
ignore_missing_imports = True

[mypy-serial.*]
ignore_missing_imports = True
